name: ramayo_client_app
description: Ramayo Delivery

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  package_info: ^2.0.2
  provider: ^5.0.0
  font_awesome_flutter: ^9.1.0
  flutter_local_notifications: ^8.0.0
  intl: ^0.17.0
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
 